/**
 * 华容道关卡数据
 * 棋盘大小：5×4（列×行）
 * 坐标：x(0-4), y(0-3)
 *
 * 滑块类型：
 * - caocao: 2×2 曹操
 * - v-general: 1×2 竖将（五虎将）
 * - h-general: 2×1 横将
 * - soldier: 1×1 小兵
 */

// 滑块配色（渐变色 [起始色, 结束色]）
const BLOCK_COLORS = {
  caocao: ['#ff6b6b', '#ee5a5a'],      // 红色 - 曹操
  'v-general': ['#4ecdc4', '#44b3ab'], // 青色 - 竖将
  'h-general': ['#ffe66d', '#ffd93d'], // 黄色 - 横将
  soldier: ['#95e1d3', '#7ed7c6'],     // 绿色 - 小兵
};

const LEVELS = [
  {
    id: 1,
    name: '初出茅庐',
    blocks: [
      { id: 'caocao', type: 'caocao', x: 1, y: 0, width: 2, height: 2 },
      { id: 'v1', type: 'v-general', x: 0, y: 0, width: 1, height: 2 },
      { id: 'v2', type: 'v-general', x: 4, y: 0, width: 1, height: 2 },
      { id: 'h1', type: 'h-general', x: 1, y: 2, width: 2, height: 1 },
      { id: 's1', type: 'soldier', x: 0, y: 2, width: 1, height: 1 },
      { id: 's2', type: 'soldier', x: 0, y: 3, width: 1, height: 1 },
      { id: 's3', type: 'soldier', x: 4, y: 3, width: 1, height: 1 },
    ],
    minSteps: 5,
  },
  {
    id: 2,
    name: '峰回路转',
    blocks: [
      { id: 'caocao', type: 'caocao', x: 1, y: 1, width: 2, height: 2 },
      { id: 'v1', type: 'v-general', x: 0, y: 0, width: 1, height: 2 },
      { id: 'v2', type: 'v-general', x: 4, y: 0, width: 1, height: 2 },
      { id: 'h1', type: 'h-general', x: 1, y: 0, width: 2, height: 1 },
      { id: 'v3', type: 'v-general', x: 0, y: 2, width: 1, height: 2 },
      { id: 's1', type: 'soldier', x: 3, y: 2, width: 1, height: 1 },
      { id: 's2', type: 'soldier', x: 4, y: 2, width: 1, height: 1 },
      { id: 's3', type: 'soldier', x: 2, y: 3, width: 1, height: 1 },
    ],
    minSteps: 3,
  },
  {
    id: 3,
    name: '一马平川',
    blocks: [
      { id: 'caocao', type: 'caocao', x: 2, y: 2, width: 2, height: 2 },
      { id: 'v1', type: 'v-general', x: 0, y: 0, width: 1, height: 2 },
      { id: 'v2', type: 'v-general', x: 0, y: 2, width: 1, height: 2 },
      { id: 'h1', type: 'h-general', x: 2, y: 0, width: 2, height: 1 },
      { id: 'h2', type: 'h-general', x: 2, y: 1, width: 2, height: 1 },
      { id: 's1', type: 'soldier', x: 4, y: 0, width: 1, height: 1 },
      { id: 's2', type: 'soldier', x: 4, y: 2, width: 1, height: 1 },
      { id: 's3', type: 'soldier', x: 1, y: 1, width: 1, height: 1 },
      { id: 's4', type: 'soldier', x: 1, y: 2, width: 1, height: 1 },
      { id: 's5', type: 'soldier', x: 4, y: 3, width: 1, height: 1 },
      { id: 's6', type: 'soldier', x: 4, y: 1, width: 1, height: 1 },
    ],
    minSteps: 4,
  },
  {
    id: 4,
    name: '走投无路',
    blocks: [
      { id: 'caocao', type: 'caocao', x: 1, y: 1, width: 2, height: 2 },
      { id: 'v1', type: 'v-general', x: 0, y: 0, width: 1, height: 2 },
      { id: 'v2', type: 'v-general', x: 4, y: 0, width: 1, height: 2 },
      { id: 'h1', type: 'h-general', x: 1, y: 0, width: 2, height: 1 },
      { id: 'h2', type: 'h-general', x: 1, y: 3, width: 2, height: 1 },
      { id: 's1', type: 'soldier', x: 0, y: 2, width: 1, height: 1 },
      { id: 's2', type: 'soldier', x: 3, y: 2, width: 1, height: 1 },
      { id: 's3', type: 'soldier', x: 4, y: 2, width: 1, height: 1 },
    ],
    minSteps: 4,
  },
  {
    id: 5,
    name: '轻舟已过',
    blocks: [
      { id: 'caocao', type: 'caocao', x: 1, y: 1, width: 2, height: 2 },
      { id: 'v1', type: 'v-general', x: 0, y: 0, width: 1, height: 2 },
      { id: 'v2', type: 'v-general', x: 4, y: 0, width: 1, height: 2 },
      { id: 'v3', type: 'v-general', x: 3, y: 1, width: 1, height: 2 },
      { id: 'h1', type: 'h-general', x: 1, y: 0, width: 2, height: 1 },
      { id: 's1', type: 'soldier', x: 0, y: 3, width: 1, height: 1 },
      { id: 's2', type: 'soldier', x: 3, y: 0, width: 1, height: 1 },
      { id: 's3', type: 'soldier', x: 4, y: 2, width: 1, height: 1 },
      { id: 's4', type: 'soldier', x: 0, y: 2, width: 1, height: 1 },
      { id: 's5', type: 'soldier', x: 1, y: 3, width: 1, height: 1 },
      { id: 's6', type: 'soldier', x: 3, y: 3, width: 1, height: 1 },
    ],
    minSteps: 5,
  },
  {
    id: 6,
    name: '小试牛刀',
    blocks: [
      { id: 'caocao', type: 'caocao', x: 0, y: 2, width: 2, height: 2 },
      { id: 'v1', type: 'v-general', x: 2, y: 0, width: 1, height: 2 },
      { id: 'v2', type: 'v-general', x: 3, y: 1, width: 1, height: 2 },
      { id: 'v3', type: 'v-general', x: 0, y: 0, width: 1, height: 2 },
      { id: 'v4', type: 'v-general', x: 4, y: 0, width: 1, height: 2 },
      { id: 's1', type: 'soldier', x: 4, y: 3, width: 1, height: 1 },
      { id: 's2', type: 'soldier', x: 2, y: 3, width: 1, height: 1 },
      { id: 's3', type: 'soldier', x: 1, y: 1, width: 1, height: 1 },
      { id: 's4', type: 'soldier', x: 1, y: 0, width: 1, height: 1 },
      { id: 's5', type: 'soldier', x: 4, y: 2, width: 1, height: 1 },
      { id: 's6', type: 'soldier', x: 2, y: 2, width: 1, height: 1 },
    ],
    minSteps: 5,
  },
  {
    id: 7,
    name: '指挥若定',
    blocks: [
      { id: 'caocao', type: 'caocao', x: 1, y: 1, width: 2, height: 2 },
      { id: 'h1', type: 'h-general', x: 0, y: 0, width: 2, height: 1 },
      { id: 'h2', type: 'h-general', x: 3, y: 0, width: 2, height: 1 },
      { id: 'v1', type: 'v-general', x: 0, y: 1, width: 1, height: 2 },
      { id: 'v2', type: 'v-general', x: 4, y: 1, width: 1, height: 2 },
      { id: 's1', type: 'soldier', x: 2, y: 0, width: 1, height: 1 },
      { id: 's2', type: 'soldier', x: 0, y: 3, width: 1, height: 1 },
      { id: 's3', type: 'soldier', x: 1, y: 3, width: 1, height: 1 },
      { id: 's4', type: 'soldier', x: 3, y: 3, width: 1, height: 1 },
      { id: 's5', type: 'soldier', x: 4, y: 3, width: 1, height: 1 },
    ],
    minSteps: 5,
  },
  {
    id: 8,
    name: '将拥曹营',
    blocks: [
      { id: 'caocao', type: 'caocao', x: 1, y: 1, width: 2, height: 2 },
      { id: 'h1', type: 'h-general', x: 0, y: 0, width: 2, height: 1 },
      { id: 'h2', type: 'h-general', x: 3, y: 0, width: 2, height: 1 },
      { id: 'h3', type: 'h-general', x: 1, y: 3, width: 2, height: 1 },
      { id: 'v1', type: 'v-general', x: 0, y: 1, width: 1, height: 2 },
      { id: 'v2', type: 'v-general', x: 4, y: 1, width: 1, height: 2 },
      { id: 's1', type: 'soldier', x: 0, y: 3, width: 1, height: 1 },
      { id: 's2', type: 'soldier', x: 3, y: 3, width: 1, height: 1 },
    ],
    minSteps: 5,
  },
  {
    id: 9,
    name: '柳暗花明',
    blocks: [
      { id: 'caocao', type: 'caocao', x: 1, y: 1, width: 2, height: 2 },
      { id: 'h1', type: 'h-general', x: 0, y: 0, width: 2, height: 1 },
      { id: 'h2', type: 'h-general', x: 3, y: 0, width: 2, height: 1 },
      { id: 'v1', type: 'v-general', x: 0, y: 1, width: 1, height: 2 },
      { id: 'v2', type: 'v-general', x: 4, y: 1, width: 1, height: 2 },
      { id: 's1', type: 'soldier', x: 2, y: 0, width: 1, height: 1 },
      { id: 's2', type: 'soldier', x: 1, y: 3, width: 1, height: 1 },
      { id: 's3', type: 'soldier', x: 2, y: 3, width: 1, height: 1 },
      { id: 's4', type: 'soldier', x: 3, y: 3, width: 1, height: 1 },
    ],
    minSteps: 5,
  },
  {
    id: 10,
    name: '拨云见日',
    blocks: [
      { id: 'caocao', type: 'caocao', x: 0, y: 2, width: 2, height: 2 },
      { id: 'v1', type: 'v-general', x: 1, y: 0, width: 1, height: 2 },
      { id: 'v2', type: 'v-general', x: 0, y: 0, width: 1, height: 2 },
      { id: 'v3', type: 'v-general', x: 2, y: 2, width: 1, height: 2 },
      { id: 'h1', type: 'h-general', x: 2, y: 0, width: 2, height: 1 },
      { id: 'h2', type: 'h-general', x: 3, y: 2, width: 2, height: 1 },
      { id: 's1', type: 'soldier', x: 4, y: 3, width: 1, height: 1 },
      { id: 's2', type: 'soldier', x: 3, y: 1, width: 1, height: 1 },
      { id: 's3', type: 'soldier', x: 4, y: 0, width: 1, height: 1 },
      { id: 's4', type: 'soldier', x: 3, y: 3, width: 1, height: 1 },
    ],
    minSteps: 6,
  },
  {
    id: 11,
    name: '左右逢源',
    blocks: [
      { id: 'caocao', type: 'caocao', x: 2, y: 2, width: 2, height: 2 },
      { id: 'v1', type: 'v-general', x: 0, y: 2, width: 1, height: 2 },
      { id: 'v2', type: 'v-general', x: 4, y: 0, width: 1, height: 2 },
      { id: 'h1', type: 'h-general', x: 2, y: 0, width: 2, height: 1 },
      { id: 'h2', type: 'h-general', x: 1, y: 1, width: 2, height: 1 },
      { id: 's1', type: 'soldier', x: 1, y: 0, width: 1, height: 1 },
      { id: 's2', type: 'soldier', x: 1, y: 3, width: 1, height: 1 },
      { id: 's3', type: 'soldier', x: 0, y: 0, width: 1, height: 1 },
      { id: 's4', type: 'soldier', x: 4, y: 3, width: 1, height: 1 },
      { id: 's5', type: 'soldier', x: 4, y: 2, width: 1, height: 1 },
      { id: 's6', type: 'soldier', x: 1, y: 2, width: 1, height: 1 },
    ],
    minSteps: 6,
  },
  {
    id: 12,
    name: '一夫当关',
    blocks: [
      { id: 'caocao', type: 'caocao', x: 1, y: 1, width: 2, height: 2 },
      { id: 'v1', type: 'v-general', x: 0, y: 0, width: 1, height: 2 },
      { id: 'v2', type: 'v-general', x: 4, y: 0, width: 1, height: 2 },
      { id: 'h1', type: 'h-general', x: 1, y: 0, width: 2, height: 1 },
      { id: 's1', type: 'soldier', x: 0, y: 2, width: 1, height: 1 },
      { id: 's2', type: 'soldier', x: 3, y: 2, width: 1, height: 1 },
      { id: 's3', type: 'soldier', x: 4, y: 2, width: 1, height: 1 },
      { id: 's4', type: 'soldier', x: 0, y: 3, width: 1, height: 1 },
      { id: 's5', type: 'soldier', x: 1, y: 3, width: 1, height: 1 },
      { id: 's6', type: 'soldier', x: 2, y: 3, width: 1, height: 1 },
    ],
    minSteps: 6,
  },
  {
    id: 13,
    name: '见缝插针',
    blocks: [
      { id: 'caocao', type: 'caocao', x: 1, y: 1, width: 2, height: 2 },
      { id: 'v1', type: 'v-general', x: 0, y: 0, width: 1, height: 2 },
      { id: 'v2', type: 'v-general', x: 4, y: 2, width: 1, height: 2 },
      { id: 'v3', type: 'v-general', x: 3, y: 2, width: 1, height: 2 },
      { id: 'h1', type: 'h-general', x: 3, y: 0, width: 2, height: 1 },
      { id: 's1', type: 'soldier', x: 4, y: 1, width: 1, height: 1 },
      { id: 's2', type: 'soldier', x: 1, y: 0, width: 1, height: 1 },
      { id: 's3', type: 'soldier', x: 2, y: 3, width: 1, height: 1 },
      { id: 's4', type: 'soldier', x: 0, y: 2, width: 1, height: 1 },
      { id: 's5', type: 'soldier', x: 0, y: 3, width: 1, height: 1 },
      { id: 's6', type: 'soldier', x: 3, y: 1, width: 1, height: 1 },
    ],
    minSteps: 7,
  },
  {
    id: 14,
    name: '步步为营',
    blocks: [
      { id: 'caocao', type: 'caocao', x: 2, y: 1, width: 2, height: 2 },
      { id: 'v1', type: 'v-general', x: 4, y: 0, width: 1, height: 2 },
      { id: 'v2', type: 'v-general', x: 0, y: 1, width: 1, height: 2 },
      { id: 'v3', type: 'v-general', x: 4, y: 2, width: 1, height: 2 },
      { id: 'v4', type: 'v-general', x: 1, y: 0, width: 1, height: 2 },
      { id: 'v5', type: 'v-general', x: 1, y: 2, width: 1, height: 2 },
      { id: 's1', type: 'soldier', x: 2, y: 0, width: 1, height: 1 },
      { id: 's2', type: 'soldier', x: 3, y: 0, width: 1, height: 1 },
      { id: 's3', type: 'soldier', x: 0, y: 3, width: 1, height: 1 },
    ],
    minSteps: 8,
  },
  {
    id: 15,
    name: '层层设防',
    blocks: [
      { id: 'caocao', type: 'caocao', x: 1, y: 1, width: 2, height: 2 },
      { id: 'h1', type: 'h-general', x: 0, y: 0, width: 2, height: 1 },
      { id: 'h2', type: 'h-general', x: 3, y: 0, width: 2, height: 1 },
      { id: 'h3', type: 'h-general', x: 0, y: 3, width: 2, height: 1 },
      { id: 'v1', type: 'v-general', x: 0, y: 1, width: 1, height: 2 },
      { id: 'v2', type: 'v-general', x: 4, y: 1, width: 1, height: 2 },
      { id: 's1', type: 'soldier', x: 2, y: 0, width: 1, height: 1 },
      { id: 's2', type: 'soldier', x: 3, y: 2, width: 1, height: 1 },
      { id: 's3', type: 'soldier', x: 4, y: 3, width: 1, height: 1 },
    ],
    minSteps: 8,
  },
  {
    id: 16,
    name: '四面埋伏',
    blocks: [
      { id: 'caocao', type: 'caocao', x: 1, y: 1, width: 2, height: 2 },
      { id: 'h1', type: 'h-general', x: 0, y: 0, width: 2, height: 1 },
      { id: 'h2', type: 'h-general', x: 3, y: 0, width: 2, height: 1 },
      { id: 'h3', type: 'h-general', x: 0, y: 3, width: 2, height: 1 },
      { id: 'v1', type: 'v-general', x: 0, y: 1, width: 1, height: 2 },
      { id: 'v2', type: 'v-general', x: 4, y: 1, width: 1, height: 2 },
      { id: 's1', type: 'soldier', x: 2, y: 0, width: 1, height: 1 },
      { id: 's2', type: 'soldier', x: 3, y: 2, width: 1, height: 1 },
      { id: 's3', type: 'soldier', x: 2, y: 3, width: 1, height: 1 },
    ],
    minSteps: 8,
  },
  {
    id: 17,
    name: '围魏救赵',
    blocks: [
      { id: 'caocao', type: 'caocao', x: 2, y: 2, width: 2, height: 2 },
      { id: 'v1', type: 'v-general', x: 4, y: 2, width: 1, height: 2 },
      { id: 'h1', type: 'h-general', x: 3, y: 0, width: 2, height: 1 },
      { id: 'h2', type: 'h-general', x: 0, y: 0, width: 2, height: 1 },
      { id: 'h3', type: 'h-general', x: 2, y: 1, width: 2, height: 1 },
      { id: 's1', type: 'soldier', x: 0, y: 3, width: 1, height: 1 },
      { id: 's2', type: 'soldier', x: 1, y: 1, width: 1, height: 1 },
      { id: 's3', type: 'soldier', x: 1, y: 3, width: 1, height: 1 },
      { id: 's4', type: 'soldier', x: 2, y: 0, width: 1, height: 1 },
      { id: 's5', type: 'soldier', x: 1, y: 2, width: 1, height: 1 },
      { id: 's6', type: 'soldier', x: 0, y: 2, width: 1, height: 1 },
    ],
    minSteps: 8,
  },
  {
    id: 18,
    name: '暗度陈仓',
    blocks: [
      { id: 'caocao', type: 'caocao', x: 0, y: 2, width: 2, height: 2 },
      { id: 'v1', type: 'v-general', x: 4, y: 1, width: 1, height: 2 },
      { id: 'v2', type: 'v-general', x: 3, y: 1, width: 1, height: 2 },
      { id: 'v3', type: 'v-general', x: 2, y: 2, width: 1, height: 2 },
      { id: 'h1', type: 'h-general', x: 0, y: 0, width: 2, height: 1 },
      { id: 's1', type: 'soldier', x: 1, y: 1, width: 1, height: 1 },
      { id: 's2', type: 'soldier', x: 2, y: 1, width: 1, height: 1 },
      { id: 's3', type: 'soldier', x: 3, y: 0, width: 1, height: 1 },
      { id: 's4', type: 'soldier', x: 4, y: 0, width: 1, height: 1 },
      { id: 's5', type: 'soldier', x: 3, y: 3, width: 1, height: 1 },
      { id: 's6', type: 'soldier', x: 2, y: 0, width: 1, height: 1 },
    ],
    minSteps: 9,
  },
  {
    id: 19,
    name: '巧渡难关',
    blocks: [
      { id: 'caocao', type: 'caocao', x: 1, y: 1, width: 2, height: 2 },
      { id: 'h1', type: 'h-general', x: 1, y: 0, width: 2, height: 1 },
      { id: 'h2', type: 'h-general', x: 1, y: 3, width: 2, height: 1 },
      { id: 'v1', type: 'v-general', x: 0, y: 0, width: 1, height: 2 },
      { id: 'v2', type: 'v-general', x: 4, y: 0, width: 1, height: 2 },
      { id: 'v3', type: 'v-general', x: 4, y: 2, width: 1, height: 2 },
      { id: 's1', type: 'soldier', x: 3, y: 2, width: 1, height: 1 },
      { id: 's2', type: 'soldier', x: 0, y: 3, width: 1, height: 1 },
      { id: 's3', type: 'soldier', x: 3, y: 3, width: 1, height: 1 },
    ],
    minSteps: 9,
  },
  {
    id: 20,
    name: '一路顺风',
    blocks: [
      { id: 'caocao', type: 'caocao', x: 1, y: 0, width: 2, height: 2 },
      { id: 'v1', type: 'v-general', x: 0, y: 0, width: 1, height: 2 },
      { id: 'v2', type: 'v-general', x: 3, y: 0, width: 1, height: 2 },
      { id: 'v3', type: 'v-general', x: 4, y: 0, width: 1, height: 2 },
      { id: 'v4', type: 'v-general', x: 0, y: 2, width: 1, height: 2 },
      { id: 's1', type: 'soldier', x: 1, y: 2, width: 1, height: 1 },
      { id: 's2', type: 'soldier', x: 2, y: 2, width: 1, height: 1 },
      { id: 's3', type: 'soldier', x: 3, y: 2, width: 1, height: 1 },
      { id: 's4', type: 'soldier', x: 4, y: 2, width: 1, height: 1 },
    ],
    minSteps: 9,
  },
  {
    id: 21,
    name: '兵分三路',
    blocks: [
      { id: 'caocao', type: 'caocao', x: 1, y: 0, width: 2, height: 2 },
      { id: 'v1', type: 'v-general', x: 0, y: 0, width: 1, height: 2 },
      { id: 'v2', type: 'v-general', x: 3, y: 0, width: 1, height: 2 },
      { id: 'h1', type: 'h-general', x: 1, y: 2, width: 2, height: 1 },
      { id: 'v3', type: 'v-general', x: 0, y: 2, width: 1, height: 2 },
      { id: 's1', type: 'soldier', x: 3, y: 2, width: 1, height: 1 },
      { id: 's2', type: 'soldier', x: 4, y: 2, width: 1, height: 1 },
      { id: 's3', type: 'soldier', x: 3, y: 3, width: 1, height: 1 },
      { id: 's4', type: 'soldier', x: 4, y: 3, width: 1, height: 1 },
    ],
    minSteps: 9,
  },
  {
    id: 22,
    name: '顺水推舟',
    blocks: [
      { id: 'caocao', type: 'caocao', x: 2, y: 2, width: 2, height: 2 },
      { id: 'v1', type: 'v-general', x: 1, y: 2, width: 1, height: 2 },
      { id: 'v2', type: 'v-general', x: 0, y: 1, width: 1, height: 2 },
      { id: 'v3', type: 'v-general', x: 4, y: 0, width: 1, height: 2 },
      { id: 'h1', type: 'h-general', x: 1, y: 0, width: 2, height: 1 },
      { id: 'h2', type: 'h-general', x: 2, y: 1, width: 2, height: 1 },
      { id: 's1', type: 'soldier', x: 4, y: 2, width: 1, height: 1 },
      { id: 's2', type: 'soldier', x: 0, y: 3, width: 1, height: 1 },
      { id: 's3', type: 'soldier', x: 1, y: 1, width: 1, height: 1 },
      { id: 's4', type: 'soldier', x: 3, y: 0, width: 1, height: 1 },
    ],
    minSteps: 10,
  },
  {
    id: 23,
    name: '四面楚歌',
    blocks: [
      { id: 'caocao', type: 'caocao', x: 1, y: 0, width: 2, height: 2 },
      { id: 'v1', type: 'v-general', x: 0, y: 0, width: 1, height: 2 },
      { id: 'v2', type: 'v-general', x: 3, y: 0, width: 1, height: 2 },
      { id: 'v3', type: 'v-general', x: 0, y: 2, width: 1, height: 2 },
      { id: 'v4', type: 'v-general', x: 3, y: 2, width: 1, height: 2 },
      { id: 'h1', type: 'h-general', x: 1, y: 2, width: 2, height: 1 },
      { id: 's1', type: 'soldier', x: 4, y: 2, width: 1, height: 1 },
      { id: 's2', type: 'soldier', x: 4, y: 3, width: 1, height: 1 },
    ],
    minSteps: 10,
  },
  {
    id: 24,
    name: '移花接木',
    blocks: [
      { id: 'caocao', type: 'caocao', x: 0, y: 2, width: 2, height: 2 },
      { id: 'v1', type: 'v-general', x: 2, y: 2, width: 1, height: 2 },
      { id: 'v2', type: 'v-general', x: 4, y: 1, width: 1, height: 2 },
      { id: 'h1', type: 'h-general', x: 2, y: 1, width: 2, height: 1 },
      { id: 'h2', type: 'h-general', x: 0, y: 1, width: 2, height: 1 },
      { id: 'h3', type: 'h-general', x: 3, y: 0, width: 2, height: 1 },
      { id: 's1', type: 'soldier', x: 3, y: 2, width: 1, height: 1 },
      { id: 's2', type: 'soldier', x: 4, y: 3, width: 1, height: 1 },
      { id: 's3', type: 'soldier', x: 0, y: 0, width: 1, height: 1 },
      { id: 's4', type: 'soldier', x: 3, y: 3, width: 1, height: 1 },
    ],
    minSteps: 11,
  },
  {
    id: 25,
    name: '峰回路转二',
    blocks: [
      { id: 'caocao', type: 'caocao', x: 0, y: 2, width: 2, height: 2 },
      { id: 'v1', type: 'v-general', x: 0, y: 0, width: 1, height: 2 },
      { id: 'v2', type: 'v-general', x: 3, y: 1, width: 1, height: 2 },
      { id: 'v3', type: 'v-general', x: 2, y: 1, width: 1, height: 2 },
      { id: 'h1', type: 'h-general', x: 3, y: 3, width: 2, height: 1 },
      { id: 'h2', type: 'h-general', x: 2, y: 0, width: 2, height: 1 },
      { id: 's1', type: 'soldier', x: 1, y: 0, width: 1, height: 1 },
      { id: 's2', type: 'soldier', x: 2, y: 3, width: 1, height: 1 },
      { id: 's3', type: 'soldier', x: 4, y: 1, width: 1, height: 1 },
      { id: 's4', type: 'soldier', x: 4, y: 2, width: 1, height: 1 },
    ],
    minSteps: 12,
  },
  {
    id: 26,
    name: '柳暗花明二',
    blocks: [
      { id: 'caocao', type: 'caocao', x: 2, y: 2, width: 2, height: 2 },
      { id: 'v1', type: 'v-general', x: 0, y: 2, width: 1, height: 2 },
      { id: 'v2', type: 'v-general', x: 1, y: 0, width: 1, height: 2 },
      { id: 'v3', type: 'v-general', x: 4, y: 0, width: 1, height: 2 },
      { id: 'h1', type: 'h-general', x: 2, y: 0, width: 2, height: 1 },
      { id: 's1', type: 'soldier', x: 4, y: 2, width: 1, height: 1 },
      { id: 's2', type: 'soldier', x: 1, y: 3, width: 1, height: 1 },
      { id: 's3', type: 'soldier', x: 3, y: 1, width: 1, height: 1 },
      { id: 's4', type: 'soldier', x: 0, y: 1, width: 1, height: 1 },
      { id: 's5', type: 'soldier', x: 0, y: 0, width: 1, height: 1 },
      { id: 's6', type: 'soldier', x: 4, y: 3, width: 1, height: 1 },
    ],
    minSteps: 12,
  },
  {
    id: 27,
    name: '兵临城下',
    blocks: [
      { id: 'caocao', type: 'caocao', x: 1, y: 1, width: 2, height: 2 },
      { id: 'v1', type: 'v-general', x: 0, y: 0, width: 1, height: 2 },
      { id: 'v2', type: 'v-general', x: 4, y: 1, width: 1, height: 2 },
      { id: 'h1', type: 'h-general', x: 0, y: 3, width: 2, height: 1 },
      { id: 'h2', type: 'h-general', x: 3, y: 0, width: 2, height: 1 },
      { id: 'v3', type: 'v-general', x: 3, y: 2, width: 1, height: 2 },
      { id: 's1', type: 'soldier', x: 2, y: 0, width: 1, height: 1 },
      { id: 's2', type: 'soldier', x: 0, y: 2, width: 1, height: 1 },
      { id: 's3', type: 'soldier', x: 2, y: 3, width: 1, height: 1 },
    ],
    minSteps: 12,
  },
  {
    id: 28,
    name: '横刀立马',
    blocks: [
      { id: 'caocao', type: 'caocao', x: 1, y: 0, width: 2, height: 2 },
      { id: 'v1', type: 'v-general', x: 0, y: 0, width: 1, height: 2 },
      { id: 'v2', type: 'v-general', x: 3, y: 0, width: 1, height: 2 },
      { id: 'v3', type: 'v-general', x: 0, y: 2, width: 1, height: 2 },
      { id: 'v4', type: 'v-general', x: 3, y: 2, width: 1, height: 2 },
      { id: 'h1', type: 'h-general', x: 1, y: 2, width: 2, height: 1 },
      { id: 's1', type: 'soldier', x: 1, y: 3, width: 1, height: 1 },
      { id: 's2', type: 'soldier', x: 2, y: 3, width: 1, height: 1 },
    ],
    minSteps: 12,
  },
  {
    id: 29,
    name: '兵行险着',
    blocks: [
      { id: 'caocao', type: 'caocao', x: 0, y: 1, width: 2, height: 2 },
      { id: 'v1', type: 'v-general', x: 4, y: 2, width: 1, height: 2 },
      { id: 'v2', type: 'v-general', x: 4, y: 0, width: 1, height: 2 },
      { id: 'v3', type: 'v-general', x: 3, y: 2, width: 1, height: 2 },
      { id: 'v4', type: 'v-general', x: 3, y: 0, width: 1, height: 2 },
      { id: 's1', type: 'soldier', x: 1, y: 0, width: 1, height: 1 },
      { id: 's2', type: 'soldier', x: 1, y: 3, width: 1, height: 1 },
      { id: 's3', type: 'soldier', x: 0, y: 0, width: 1, height: 1 },
      { id: 's4', type: 'soldier', x: 2, y: 1, width: 1, height: 1 },
      { id: 's5', type: 'soldier', x: 2, y: 3, width: 1, height: 1 },
      { id: 's6', type: 'soldier', x: 2, y: 2, width: 1, height: 1 },
    ],
    minSteps: 13,
  },
  {
    id: 30,
    name: '车马盈门',
    blocks: [
      { id: 'caocao', type: 'caocao', x: 1, y: 1, width: 2, height: 2 },
      { id: 'v1', type: 'v-general', x: 0, y: 0, width: 1, height: 2 },
      { id: 'v2', type: 'v-general', x: 3, y: 1, width: 1, height: 2 },
      { id: 'v3', type: 'v-general', x: 4, y: 1, width: 1, height: 2 },
      { id: 'h1', type: 'h-general', x: 0, y: 3, width: 2, height: 1 },
      { id: 'h2', type: 'h-general', x: 3, y: 0, width: 2, height: 1 },
      { id: 's1', type: 'soldier', x: 4, y: 3, width: 1, height: 1 },
      { id: 's2', type: 'soldier', x: 0, y: 2, width: 1, height: 1 },
      { id: 's3', type: 'soldier', x: 1, y: 0, width: 1, height: 1 },
      { id: 's4', type: 'soldier', x: 3, y: 3, width: 1, height: 1 },
    ],
    minSteps: 14,
  },
  {
    id: 31,
    name: '关山初渡',
    blocks: [
      { id: 'caocao', type: 'caocao', x: 3, y: 2, width: 2, height: 2 },
      { id: 'v1', type: 'v-general', x: 2, y: 2, width: 1, height: 2 },
      { id: 'v2', type: 'v-general', x: 2, y: 0, width: 1, height: 2 },
      { id: 'v3', type: 'v-general', x: 0, y: 1, width: 1, height: 2 },
      { id: 'v4', type: 'v-general', x: 4, y: 0, width: 1, height: 2 },
      { id: 's1', type: 'soldier', x: 3, y: 0, width: 1, height: 1 },
      { id: 's2', type: 'soldier', x: 0, y: 0, width: 1, height: 1 },
      { id: 's3', type: 'soldier', x: 3, y: 1, width: 1, height: 1 },
      { id: 's4', type: 'soldier', x: 1, y: 0, width: 1, height: 1 },
      { id: 's5', type: 'soldier', x: 1, y: 2, width: 1, height: 1 },
      { id: 's6', type: 'soldier', x: 0, y: 3, width: 1, height: 1 },
    ],
    minSteps: 14,
  },
  {
    id: 32,
    name: '兵贵神速',
    blocks: [
      { id: 'caocao', type: 'caocao', x: 1, y: 0, width: 2, height: 2 },
      { id: 'v1', type: 'v-general', x: 0, y: 0, width: 1, height: 2 },
      { id: 'v2', type: 'v-general', x: 3, y: 0, width: 1, height: 2 },
      { id: 'v3', type: 'v-general', x: 0, y: 2, width: 1, height: 2 },
      { id: 'v4', type: 'v-general', x: 3, y: 2, width: 1, height: 2 },
      { id: 's1', type: 'soldier', x: 1, y: 2, width: 1, height: 1 },
      { id: 's2', type: 'soldier', x: 2, y: 2, width: 1, height: 1 },
      { id: 's3', type: 'soldier', x: 1, y: 3, width: 1, height: 1 },
      { id: 's4', type: 'soldier', x: 2, y: 3, width: 1, height: 1 },
    ],
    minSteps: 14,
  },
  {
    id: 33,
    name: '独木难支',
    blocks: [
      { id: 'caocao', type: 'caocao', x: 1, y: 0, width: 2, height: 2 },
      { id: 'v1', type: 'v-general', x: 0, y: 0, width: 1, height: 2 },
      { id: 'v2', type: 'v-general', x: 3, y: 0, width: 1, height: 2 },
      { id: 'h1', type: 'h-general', x: 1, y: 2, width: 2, height: 1 },
      { id: 's1', type: 'soldier', x: 0, y: 2, width: 1, height: 1 },
      { id: 's2', type: 'soldier', x: 3, y: 2, width: 1, height: 1 },
      { id: 's3', type: 'soldier', x: 0, y: 3, width: 1, height: 1 },
      { id: 's4', type: 'soldier', x: 1, y: 3, width: 1, height: 1 },
      { id: 's5', type: 'soldier', x: 2, y: 3, width: 1, height: 1 },
      { id: 's6', type: 'soldier', x: 3, y: 3, width: 1, height: 1 },
    ],
    minSteps: 14,
  },
  {
    id: 34,
    name: '两翼齐飞',
    blocks: [
      { id: 'caocao', type: 'caocao', x: 0, y: 2, width: 2, height: 2 },
      { id: 'v1', type: 'v-general', x: 3, y: 0, width: 1, height: 2 },
      { id: 'h1', type: 'h-general', x: 1, y: 1, width: 2, height: 1 },
      { id: 'h2', type: 'h-general', x: 0, y: 0, width: 2, height: 1 },
      { id: 'h3', type: 'h-general', x: 2, y: 3, width: 2, height: 1 },
      { id: 'h4', type: 'h-general', x: 2, y: 2, width: 2, height: 1 },
      { id: 's1', type: 'soldier', x: 2, y: 0, width: 1, height: 1 },
      { id: 's2', type: 'soldier', x: 4, y: 2, width: 1, height: 1 },
      { id: 's3', type: 'soldier', x: 4, y: 3, width: 1, height: 1 },
      { id: 's4', type: 'soldier', x: 4, y: 1, width: 1, height: 1 },
    ],
    minSteps: 15,
  },
  {
    id: 35,
    name: '月下排兵',
    blocks: [
      { id: 'caocao', type: 'caocao', x: 3, y: 2, width: 2, height: 2 },
      { id: 'v1', type: 'v-general', x: 2, y: 2, width: 1, height: 2 },
      { id: 'v2', type: 'v-general', x: 0, y: 2, width: 1, height: 2 },
      { id: 'v3', type: 'v-general', x: 2, y: 0, width: 1, height: 2 },
      { id: 'v4', type: 'v-general', x: 1, y: 0, width: 1, height: 2 },
      { id: 'v5', type: 'v-general', x: 3, y: 0, width: 1, height: 2 },
      { id: 's1', type: 'soldier', x: 4, y: 1, width: 1, height: 1 },
      { id: 's2', type: 'soldier', x: 1, y: 3, width: 1, height: 1 },
      { id: 's3', type: 'soldier', x: 4, y: 0, width: 1, height: 1 },
    ],
    minSteps: 15,
  },
  {
    id: 36,
    name: '星罗棋布',
    blocks: [
      { id: 'caocao', type: 'caocao', x: 3, y: 2, width: 2, height: 2 },
      { id: 'v1', type: 'v-general', x: 1, y: 1, width: 1, height: 2 },
      { id: 'v2', type: 'v-general', x: 0, y: 1, width: 1, height: 2 },
      { id: 'v3', type: 'v-general', x: 4, y: 0, width: 1, height: 2 },
      { id: 'h1', type: 'h-general', x: 2, y: 1, width: 2, height: 1 },
      { id: 's1', type: 'soldier', x: 3, y: 0, width: 1, height: 1 },
      { id: 's2', type: 'soldier', x: 1, y: 3, width: 1, height: 1 },
      { id: 's3', type: 'soldier', x: 2, y: 0, width: 1, height: 1 },
      { id: 's4', type: 'soldier', x: 0, y: 0, width: 1, height: 1 },
      { id: 's5', type: 'soldier', x: 2, y: 2, width: 1, height: 1 },
      { id: 's6', type: 'soldier', x: 0, y: 3, width: 1, height: 1 },
    ],
    minSteps: 15,
  },
  {
    id: 37,
    name: '铁索横江',
    blocks: [
      { id: 'caocao', type: 'caocao', x: 3, y: 2, width: 2, height: 2 },
      { id: 'v1', type: 'v-general', x: 1, y: 0, width: 1, height: 2 },
      { id: 'v2', type: 'v-general', x: 4, y: 0, width: 1, height: 2 },
      { id: 'v3', type: 'v-general', x: 3, y: 0, width: 1, height: 2 },
      { id: 'v4', type: 'v-general', x: 0, y: 0, width: 1, height: 2 },
      { id: 's1', type: 'soldier', x: 1, y: 3, width: 1, height: 1 },
      { id: 's2', type: 'soldier', x: 1, y: 2, width: 1, height: 1 },
      { id: 's3', type: 'soldier', x: 2, y: 1, width: 1, height: 1 },
      { id: 's4', type: 'soldier', x: 0, y: 3, width: 1, height: 1 },
      { id: 's5', type: 'soldier', x: 2, y: 0, width: 1, height: 1 },
      { id: 's6', type: 'soldier', x: 2, y: 2, width: 1, height: 1 },
    ],
    minSteps: 15,
  },
  {
    id: 38,
    name: '三军会师',
    blocks: [
      { id: 'caocao', type: 'caocao', x: 2, y: 1, width: 2, height: 2 },
      { id: 'v1', type: 'v-general', x: 4, y: 2, width: 1, height: 2 },
      { id: 'v2', type: 'v-general', x: 0, y: 2, width: 1, height: 2 },
      { id: 'v3', type: 'v-general', x: 4, y: 0, width: 1, height: 2 },
      { id: 'v4', type: 'v-general', x: 1, y: 2, width: 1, height: 2 },
      { id: 's1', type: 'soldier', x: 1, y: 1, width: 1, height: 1 },
      { id: 's2', type: 'soldier', x: 3, y: 3, width: 1, height: 1 },
      { id: 's3', type: 'soldier', x: 3, y: 0, width: 1, height: 1 },
      { id: 's4', type: 'soldier', x: 2, y: 0, width: 1, height: 1 },
      { id: 's5', type: 'soldier', x: 2, y: 3, width: 1, height: 1 },
      { id: 's6', type: 'soldier', x: 0, y: 1, width: 1, height: 1 },
    ],
    minSteps: 16,
  },
  {
    id: 39,
    name: '齐头并进',
    blocks: [
      { id: 'caocao', type: 'caocao', x: 1, y: 0, width: 2, height: 2 },
      { id: 'h1', type: 'h-general', x: 0, y: 2, width: 2, height: 1 },
      { id: 'h2', type: 'h-general', x: 3, y: 2, width: 2, height: 1 },
      { id: 'v1', type: 'v-general', x: 0, y: 0, width: 1, height: 2 },
      { id: 'v2', type: 'v-general', x: 4, y: 0, width: 1, height: 2 },
      { id: 's1', type: 'soldier', x: 2, y: 2, width: 1, height: 1 },
      { id: 's2', type: 'soldier', x: 0, y: 3, width: 1, height: 1 },
      { id: 's3', type: 'soldier', x: 1, y: 3, width: 1, height: 1 },
      { id: 's4', type: 'soldier', x: 3, y: 3, width: 1, height: 1 },
    ],
    minSteps: 16,
  },
  {
    id: 40,
    name: '夹道相迎',
    blocks: [
      { id: 'caocao', type: 'caocao', x: 1, y: 1, width: 2, height: 2 },
      { id: 'v1', type: 'v-general', x: 3, y: 0, width: 1, height: 2 },
      { id: 'v2', type: 'v-general', x: 0, y: 0, width: 1, height: 2 },
      { id: 'v3', type: 'v-general', x: 4, y: 1, width: 1, height: 2 },
      { id: 'h1', type: 'h-general', x: 1, y: 0, width: 2, height: 1 },
      { id: 'h2', type: 'h-general', x: 0, y: 3, width: 2, height: 1 },
      { id: 's1', type: 'soldier', x: 3, y: 2, width: 1, height: 1 },
      { id: 's2', type: 'soldier', x: 4, y: 0, width: 1, height: 1 },
      { id: 's3', type: 'soldier', x: 0, y: 2, width: 1, height: 1 },
      { id: 's4', type: 'soldier', x: 3, y: 3, width: 1, height: 1 },
    ],
    minSteps: 17,
  },
  {
    id: 41,
    name: '比翼双飞',
    blocks: [
      { id: 'caocao', type: 'caocao', x: 1, y: 0, width: 2, height: 2 },
      { id: 'v1', type: 'v-general', x: 0, y: 0, width: 1, height: 2 },
      { id: 'v2', type: 'v-general', x: 3, y: 0, width: 1, height: 2 },
      { id: 'h1', type: 'h-general', x: 0, y: 2, width: 2, height: 1 },
      { id: 'h2', type: 'h-general', x: 3, y: 2, width: 2, height: 1 },
      { id: 's1', type: 'soldier', x: 2, y: 2, width: 1, height: 1 },
      { id: 's2', type: 'soldier', x: 0, y: 3, width: 1, height: 1 },
      { id: 's3', type: 'soldier', x: 1, y: 3, width: 1, height: 1 },
      { id: 's4', type: 'soldier', x: 3, y: 3, width: 1, height: 1 },
    ],
    minSteps: 17,
  },
  {
    id: 42,
    name: '层峦叠嶂',
    blocks: [
      { id: 'caocao', type: 'caocao', x: 3, y: 2, width: 2, height: 2 },
      { id: 'v1', type: 'v-general', x: 1, y: 2, width: 1, height: 2 },
      { id: 'v2', type: 'v-general', x: 2, y: 0, width: 1, height: 2 },
      { id: 'v3', type: 'v-general', x: 0, y: 2, width: 1, height: 2 },
      { id: 'v4', type: 'v-general', x: 4, y: 0, width: 1, height: 2 },
      { id: 'v5', type: 'v-general', x: 3, y: 0, width: 1, height: 2 },
      { id: 'h1', type: 'h-general', x: 0, y: 1, width: 2, height: 1 },
      { id: 's1', type: 'soldier', x: 2, y: 2, width: 1, height: 1 },
    ],
    minSteps: 18,
  },
  {
    id: 43,
    name: '龙门初开',
    blocks: [
      { id: 'caocao', type: 'caocao', x: 0, y: 0, width: 2, height: 2 },
      { id: 'v1', type: 'v-general', x: 4, y: 2, width: 1, height: 2 },
      { id: 'v2', type: 'v-general', x: 2, y: 1, width: 1, height: 2 },
      { id: 'v3', type: 'v-general', x: 0, y: 2, width: 1, height: 2 },
      { id: 'v4', type: 'v-general', x: 3, y: 2, width: 1, height: 2 },
      { id: 'v5', type: 'v-general', x: 1, y: 2, width: 1, height: 2 },
      { id: 's1', type: 'soldier', x: 2, y: 0, width: 1, height: 1 },
      { id: 's2', type: 'soldier', x: 4, y: 0, width: 1, height: 1 },
      { id: 's3', type: 'soldier', x: 2, y: 3, width: 1, height: 1 },
    ],
    minSteps: 19,
  },
  {
    id: 44,
    name: '破釜沉舟',
    blocks: [
      { id: 'caocao', type: 'caocao', x: 1, y: 0, width: 2, height: 2 },
      { id: 'v1', type: 'v-general', x: 0, y: 0, width: 1, height: 2 },
      { id: 'v2', type: 'v-general', x: 3, y: 0, width: 1, height: 2 },
      { id: 'v3', type: 'v-general', x: 0, y: 2, width: 1, height: 2 },
      { id: 'v4', type: 'v-general', x: 4, y: 0, width: 1, height: 2 },
      { id: 's1', type: 'soldier', x: 3, y: 2, width: 1, height: 1 },
      { id: 's2', type: 'soldier', x: 4, y: 2, width: 1, height: 1 },
      { id: 's3', type: 'soldier', x: 1, y: 2, width: 1, height: 1 },
      { id: 's4', type: 'soldier', x: 2, y: 2, width: 1, height: 1 },
      { id: 's5', type: 'soldier', x: 2, y: 3, width: 1, height: 1 },
    ],
    minSteps: 19,
  },
  {
    id: 45,
    name: '纵横捭阖',
    blocks: [
      { id: 'caocao', type: 'caocao', x: 3, y: 2, width: 2, height: 2 },
      { id: 'v1', type: 'v-general', x: 1, y: 2, width: 1, height: 2 },
      { id: 'v2', type: 'v-general', x: 4, y: 0, width: 1, height: 2 },
      { id: 'v3', type: 'v-general', x: 3, y: 0, width: 1, height: 2 },
      { id: 'h1', type: 'h-general', x: 1, y: 1, width: 2, height: 1 },
      { id: 'h2', type: 'h-general', x: 0, y: 0, width: 2, height: 1 },
      { id: 's1', type: 'soldier', x: 0, y: 3, width: 1, height: 1 },
      { id: 's2', type: 'soldier', x: 0, y: 2, width: 1, height: 1 },
      { id: 's3', type: 'soldier', x: 2, y: 3, width: 1, height: 1 },
      { id: 's4', type: 'soldier', x: 2, y: 2, width: 1, height: 1 },
    ],
    minSteps: 20,
  },
  {
    id: 46,
    name: '困兽犹斗',
    blocks: [
      { id: 'caocao', type: 'caocao', x: 3, y: 2, width: 2, height: 2 },
      { id: 'v1', type: 'v-general', x: 3, y: 0, width: 1, height: 2 },
      { id: 'v2', type: 'v-general', x: 2, y: 0, width: 1, height: 2 },
      { id: 'v3', type: 'v-general', x: 0, y: 2, width: 1, height: 2 },
      { id: 'v4', type: 'v-general', x: 1, y: 2, width: 1, height: 2 },
      { id: 's1', type: 'soldier', x: 4, y: 0, width: 1, height: 1 },
      { id: 's2', type: 'soldier', x: 2, y: 2, width: 1, height: 1 },
      { id: 's3', type: 'soldier', x: 0, y: 0, width: 1, height: 1 },
      { id: 's4', type: 'soldier', x: 4, y: 1, width: 1, height: 1 },
      { id: 's5', type: 'soldier', x: 1, y: 0, width: 1, height: 1 },
      { id: 's6', type: 'soldier', x: 1, y: 1, width: 1, height: 1 },
    ],
    minSteps: 21,
  },
  {
    id: 47,
    name: '守株待兔',
    blocks: [
      { id: 'caocao', type: 'caocao', x: 1, y: 0, width: 2, height: 2 },
      { id: 'v1', type: 'v-general', x: 0, y: 0, width: 1, height: 2 },
      { id: 'v2', type: 'v-general', x: 3, y: 0, width: 1, height: 2 },
      { id: 'v3', type: 'v-general', x: 0, y: 2, width: 1, height: 2 },
      { id: 'v4', type: 'v-general', x: 4, y: 0, width: 1, height: 2 },
      { id: 'h1', type: 'h-general', x: 1, y: 2, width: 2, height: 1 },
      { id: 's1', type: 'soldier', x: 3, y: 2, width: 1, height: 1 },
      { id: 's2', type: 'soldier', x: 4, y: 2, width: 1, height: 1 },
      { id: 's3', type: 'soldier', x: 2, y: 3, width: 1, height: 1 },
    ],
    minSteps: 21,
  },
  {
    id: 48,
    name: '奇兵突围',
    blocks: [
      { id: 'caocao', type: 'caocao', x: 3, y: 2, width: 2, height: 2 },
      { id: 'v1', type: 'v-general', x: 0, y: 2, width: 1, height: 2 },
      { id: 'v2', type: 'v-general', x: 1, y: 1, width: 1, height: 2 },
      { id: 'v3', type: 'v-general', x: 2, y: 2, width: 1, height: 2 },
      { id: 'h1', type: 'h-general', x: 0, y: 0, width: 2, height: 1 },
      { id: 's1', type: 'soldier', x: 1, y: 3, width: 1, height: 1 },
      { id: 's2', type: 'soldier', x: 4, y: 0, width: 1, height: 1 },
      { id: 's3', type: 'soldier', x: 2, y: 1, width: 1, height: 1 },
      { id: 's4', type: 'soldier', x: 0, y: 1, width: 1, height: 1 },
      { id: 's5', type: 'soldier', x: 4, y: 1, width: 1, height: 1 },
      { id: 's6', type: 'soldier', x: 2, y: 0, width: 1, height: 1 },
    ],
    minSteps: 22,
  },
  {
    id: 49,
    name: '过五关',
    blocks: [
      { id: 'caocao', type: 'caocao', x: 1, y: 0, width: 2, height: 2 },
      { id: 'v1', type: 'v-general', x: 0, y: 0, width: 1, height: 2 },
      { id: 'v2', type: 'v-general', x: 3, y: 0, width: 1, height: 2 },
      { id: 'v3', type: 'v-general', x: 4, y: 0, width: 1, height: 2 },
      { id: 'v4', type: 'v-general', x: 0, y: 2, width: 1, height: 2 },
      { id: 'v5', type: 'v-general', x: 4, y: 2, width: 1, height: 2 },
      { id: 's1', type: 'soldier', x: 1, y: 2, width: 1, height: 1 },
      { id: 's2', type: 'soldier', x: 2, y: 2, width: 1, height: 1 },
      { id: 's3', type: 'soldier', x: 3, y: 2, width: 1, height: 1 },
    ],
    minSteps: 22,
  },
  {
    id: 50,
    name: '春夏秋冬',
    blocks: [
      { id: 'caocao', type: 'caocao', x: 1, y: 0, width: 2, height: 2 },
      { id: 'v1', type: 'v-general', x: 0, y: 0, width: 1, height: 2 },
      { id: 'v2', type: 'v-general', x: 3, y: 0, width: 1, height: 2 },
      { id: 'v3', type: 'v-general', x: 0, y: 2, width: 1, height: 2 },
      { id: 'v4', type: 'v-general', x: 3, y: 2, width: 1, height: 2 },
      { id: 'h1', type: 'h-general', x: 1, y: 2, width: 2, height: 1 },
      { id: 's1', type: 'soldier', x: 4, y: 0, width: 1, height: 1 },
      { id: 's2', type: 'soldier', x: 4, y: 1, width: 1, height: 1 },
      { id: 's3', type: 'soldier', x: 1, y: 3, width: 1, height: 1 },
      { id: 's4', type: 'soldier', x: 2, y: 3, width: 1, height: 1 },
    ],
    minSteps: 23,
  },
  {
    id: 51,
    name: '云开雾散',
    blocks: [
      { id: 'caocao', type: 'caocao', x: 2, y: 0, width: 2, height: 2 },
      { id: 'v1', type: 'v-general', x: 0, y: 2, width: 1, height: 2 },
      { id: 'v2', type: 'v-general', x: 2, y: 2, width: 1, height: 2 },
      { id: 'v3', type: 'v-general', x: 1, y: 2, width: 1, height: 2 },
      { id: 'v4', type: 'v-general', x: 4, y: 2, width: 1, height: 2 },
      { id: 'v5', type: 'v-general', x: 4, y: 0, width: 1, height: 2 },
      { id: 's1', type: 'soldier', x: 3, y: 3, width: 1, height: 1 },
      { id: 's2', type: 'soldier', x: 1, y: 1, width: 1, height: 1 },
      { id: 's3', type: 'soldier', x: 0, y: 1, width: 1, height: 1 },
    ],
    minSteps: 23,
  },
  {
    id: 52,
    name: '围城渐破',
    blocks: [
      { id: 'caocao', type: 'caocao', x: 0, y: 1, width: 2, height: 2 },
      { id: 'v1', type: 'v-general', x: 3, y: 0, width: 1, height: 2 },
      { id: 'v2', type: 'v-general', x: 4, y: 0, width: 1, height: 2 },
      { id: 'v3', type: 'v-general', x: 3, y: 2, width: 1, height: 2 },
      { id: 'h1', type: 'h-general', x: 1, y: 3, width: 2, height: 1 },
      { id: 's1', type: 'soldier', x: 4, y: 3, width: 1, height: 1 },
      { id: 's2', type: 'soldier', x: 2, y: 0, width: 1, height: 1 },
      { id: 's3', type: 'soldier', x: 2, y: 1, width: 1, height: 1 },
      { id: 's4', type: 'soldier', x: 2, y: 2, width: 1, height: 1 },
      { id: 's5', type: 'soldier', x: 0, y: 3, width: 1, height: 1 },
      { id: 's6', type: 'soldier', x: 4, y: 2, width: 1, height: 1 },
    ],
    minSteps: 23,
  },
  {
    id: 53,
    name: '险象环生',
    blocks: [
      { id: 'caocao', type: 'caocao', x: 1, y: 0, width: 2, height: 2 },
      { id: 'v1', type: 'v-general', x: 0, y: 1, width: 1, height: 2 },
      { id: 'v2', type: 'v-general', x: 1, y: 2, width: 1, height: 2 },
      { id: 'v3', type: 'v-general', x: 4, y: 2, width: 1, height: 2 },
      { id: 'v4', type: 'v-general', x: 3, y: 1, width: 1, height: 2 },
      { id: 'v5', type: 'v-general', x: 2, y: 2, width: 1, height: 2 },
      { id: 's1', type: 'soldier', x: 4, y: 0, width: 1, height: 1 },
      { id: 's2', type: 'soldier', x: 3, y: 3, width: 1, height: 1 },
      { id: 's3', type: 'soldier', x: 4, y: 1, width: 1, height: 1 },
    ],
    minSteps: 24,
  },
  {
    id: 54,
    name: '借道东风',
    blocks: [
      { id: 'caocao', type: 'caocao', x: 3, y: 1, width: 2, height: 2 },
      { id: 'v1', type: 'v-general', x: 1, y: 2, width: 1, height: 2 },
      { id: 'v2', type: 'v-general', x: 1, y: 0, width: 1, height: 2 },
      { id: 'v3', type: 'v-general', x: 2, y: 2, width: 1, height: 2 },
      { id: 'v4', type: 'v-general', x: 0, y: 2, width: 1, height: 2 },
      { id: 'v5', type: 'v-general', x: 0, y: 0, width: 1, height: 2 },
      { id: 's1', type: 'soldier', x: 2, y: 1, width: 1, height: 1 },
      { id: 's2', type: 'soldier', x: 4, y: 3, width: 1, height: 1 },
      { id: 's3', type: 'soldier', x: 3, y: 0, width: 1, height: 1 },
    ],
    minSteps: 25,
  },
  {
    id: 55,
    name: '四路归心',
    blocks: [
      { id: 'caocao', type: 'caocao', x: 0, y: 0, width: 2, height: 2 },
      { id: 'v1', type: 'v-general', x: 2, y: 2, width: 1, height: 2 },
      { id: 'v2', type: 'v-general', x: 4, y: 2, width: 1, height: 2 },
      { id: 'v3', type: 'v-general', x: 1, y: 2, width: 1, height: 2 },
      { id: 'v4', type: 'v-general', x: 4, y: 0, width: 1, height: 2 },
      { id: 'h1', type: 'h-general', x: 2, y: 0, width: 2, height: 1 },
      { id: 's1', type: 'soldier', x: 3, y: 3, width: 1, height: 1 },
      { id: 's2', type: 'soldier', x: 0, y: 2, width: 1, height: 1 },
      { id: 's3', type: 'soldier', x: 3, y: 1, width: 1, height: 1 },
      { id: 's4', type: 'soldier', x: 0, y: 3, width: 1, height: 1 },
    ],
    minSteps: 26,
  },
  {
    id: 56,
    name: '横桥锁钥',
    blocks: [
      { id: 'caocao', type: 'caocao', x: 2, y: 0, width: 2, height: 2 },
      { id: 'v1', type: 'v-general', x: 1, y: 2, width: 1, height: 2 },
      { id: 'v2', type: 'v-general', x: 4, y: 0, width: 1, height: 2 },
      { id: 'v3', type: 'v-general', x: 4, y: 2, width: 1, height: 2 },
      { id: 'v4', type: 'v-general', x: 2, y: 2, width: 1, height: 2 },
      { id: 's1', type: 'soldier', x: 3, y: 3, width: 1, height: 1 },
      { id: 's2', type: 'soldier', x: 0, y: 1, width: 1, height: 1 },
      { id: 's3', type: 'soldier', x: 1, y: 0, width: 1, height: 1 },
      { id: 's4', type: 'soldier', x: 3, y: 2, width: 1, height: 1 },
      { id: 's5', type: 'soldier', x: 0, y: 2, width: 1, height: 1 },
      { id: 's6', type: 'soldier', x: 1, y: 1, width: 1, height: 1 },
    ],
    minSteps: 26,
  },
  {
    id: 57,
    name: '孤军深入',
    blocks: [
      { id: 'caocao', type: 'caocao', x: 3, y: 1, width: 2, height: 2 },
      { id: 'v1', type: 'v-general', x: 2, y: 1, width: 1, height: 2 },
      { id: 'v2', type: 'v-general', x: 0, y: 2, width: 1, height: 2 },
      { id: 'v3', type: 'v-general', x: 1, y: 0, width: 1, height: 2 },
      { id: 'h1', type: 'h-general', x: 3, y: 0, width: 2, height: 1 },
      { id: 's1', type: 'soldier', x: 2, y: 3, width: 1, height: 1 },
      { id: 's2', type: 'soldier', x: 1, y: 2, width: 1, height: 1 },
      { id: 's3', type: 'soldier', x: 3, y: 3, width: 1, height: 1 },
      { id: 's4', type: 'soldier', x: 4, y: 3, width: 1, height: 1 },
      { id: 's5', type: 'soldier', x: 2, y: 0, width: 1, height: 1 },
      { id: 's6', type: 'soldier', x: 0, y: 0, width: 1, height: 1 },
    ],
    minSteps: 27,
  },
  {
    id: 58,
    name: '双线牵制',
    blocks: [
      { id: 'caocao', type: 'caocao', x: 3, y: 0, width: 2, height: 2 },
      { id: 'v1', type: 'v-general', x: 3, y: 2, width: 1, height: 2 },
      { id: 'v2', type: 'v-general', x: 4, y: 2, width: 1, height: 2 },
      { id: 'v3', type: 'v-general', x: 0, y: 0, width: 1, height: 2 },
      { id: 'v4', type: 'v-general', x: 2, y: 0, width: 1, height: 2 },
      { id: 'v5', type: 'v-general', x: 2, y: 2, width: 1, height: 2 },
      { id: 's1', type: 'soldier', x: 1, y: 2, width: 1, height: 1 },
      { id: 's2', type: 'soldier', x: 1, y: 3, width: 1, height: 1 },
      { id: 's3', type: 'soldier', x: 0, y: 3, width: 1, height: 1 },
    ],
    minSteps: 28,
  },
  {
    id: 59,
    name: '前后夹攻',
    blocks: [
      { id: 'caocao', type: 'caocao', x: 2, y: 1, width: 2, height: 2 },
      { id: 'v1', type: 'v-general', x: 4, y: 2, width: 1, height: 2 },
      { id: 'v2', type: 'v-general', x: 1, y: 2, width: 1, height: 2 },
      { id: 'v3', type: 'v-general', x: 0, y: 0, width: 1, height: 2 },
      { id: 'h1', type: 'h-general', x: 2, y: 3, width: 2, height: 1 },
      { id: 's1', type: 'soldier', x: 1, y: 1, width: 1, height: 1 },
      { id: 's2', type: 'soldier', x: 4, y: 1, width: 1, height: 1 },
      { id: 's3', type: 'soldier', x: 4, y: 0, width: 1, height: 1 },
      { id: 's4', type: 'soldier', x: 1, y: 0, width: 1, height: 1 },
      { id: 's5', type: 'soldier', x: 3, y: 0, width: 1, height: 1 },
      { id: 's6', type: 'soldier', x: 0, y: 3, width: 1, height: 1 },
    ],
    minSteps: 29,
  },
  {
    id: 60,
    name: '五虎将',
    blocks: [
      { id: 'caocao', type: 'caocao', x: 1, y: 0, width: 2, height: 2 },
      { id: 'v1', type: 'v-general', x: 0, y: 0, width: 1, height: 2 },
      { id: 'v2', type: 'v-general', x: 3, y: 0, width: 1, height: 2 },
      { id: 'h1', type: 'h-general', x: 1, y: 2, width: 2, height: 1 },
      { id: 'v3', type: 'v-general', x: 0, y: 2, width: 1, height: 2 },
      { id: 'v4', type: 'v-general', x: 4, y: 0, width: 1, height: 2 },
      { id: 's1', type: 'soldier', x: 3, y: 2, width: 1, height: 1 },
      { id: 's2', type: 'soldier', x: 4, y: 2, width: 1, height: 1 },
      { id: 's3', type: 'soldier', x: 3, y: 3, width: 1, height: 1 },
      { id: 's4', type: 'soldier', x: 4, y: 3, width: 1, height: 1 },
    ],
    minSteps: 30,
  },
  {
    id: 61,
    name: '连环设伏',
    blocks: [
      { id: 'caocao', type: 'caocao', x: 2, y: 0, width: 2, height: 2 },
      { id: 'v1', type: 'v-general', x: 0, y: 2, width: 1, height: 2 },
      { id: 'v2', type: 'v-general', x: 4, y: 0, width: 1, height: 2 },
      { id: 'v3', type: 'v-general', x: 2, y: 2, width: 1, height: 2 },
      { id: 'h1', type: 'h-general', x: 3, y: 3, width: 2, height: 1 },
      { id: 's1', type: 'soldier', x: 3, y: 2, width: 1, height: 1 },
      { id: 's2', type: 'soldier', x: 1, y: 2, width: 1, height: 1 },
      { id: 's3', type: 'soldier', x: 1, y: 3, width: 1, height: 1 },
      { id: 's4', type: 'soldier', x: 1, y: 0, width: 1, height: 1 },
      { id: 's5', type: 'soldier', x: 4, y: 2, width: 1, height: 1 },
      { id: 's6', type: 'soldier', x: 0, y: 1, width: 1, height: 1 },
    ],
    minSteps: 30,
  },
  {
    id: 62,
    name: '危局求生',
    blocks: [
      { id: 'caocao', type: 'caocao', x: 0, y: 0, width: 2, height: 2 },
      { id: 'v1', type: 'v-general', x: 3, y: 1, width: 1, height: 2 },
      { id: 'v2', type: 'v-general', x: 2, y: 2, width: 1, height: 2 },
      { id: 'v3', type: 'v-general', x: 4, y: 1, width: 1, height: 2 },
      { id: 'h1', type: 'h-general', x: 0, y: 2, width: 2, height: 1 },
      { id: 's1', type: 'soldier', x: 0, y: 3, width: 1, height: 1 },
      { id: 's2', type: 'soldier', x: 2, y: 1, width: 1, height: 1 },
      { id: 's3', type: 'soldier', x: 3, y: 3, width: 1, height: 1 },
      { id: 's4', type: 'soldier', x: 4, y: 3, width: 1, height: 1 },
      { id: 's5', type: 'soldier', x: 3, y: 0, width: 1, height: 1 },
      { id: 's6', type: 'soldier', x: 2, y: 0, width: 1, height: 1 },
    ],
    minSteps: 31,
  },
  {
    id: 63,
    name: '绝处逢生',
    blocks: [
      { id: 'caocao', type: 'caocao', x: 3, y: 1, width: 2, height: 2 },
      { id: 'v1', type: 'v-general', x: 2, y: 2, width: 1, height: 2 },
      { id: 'h1', type: 'h-general', x: 0, y: 3, width: 2, height: 1 },
      { id: 'h2', type: 'h-general', x: 3, y: 0, width: 2, height: 1 },
      { id: 'h3', type: 'h-general', x: 1, y: 0, width: 2, height: 1 },
      { id: 's1', type: 'soldier', x: 1, y: 2, width: 1, height: 1 },
      { id: 's2', type: 'soldier', x: 0, y: 1, width: 1, height: 1 },
      { id: 's3', type: 'soldier', x: 1, y: 1, width: 1, height: 1 },
      { id: 's4', type: 'soldier', x: 4, y: 3, width: 1, height: 1 },
      { id: 's5', type: 'soldier', x: 3, y: 3, width: 1, height: 1 },
      { id: 's6', type: 'soldier', x: 2, y: 1, width: 1, height: 1 },
    ],
    minSteps: 33,
  },
  {
    id: 64,
    name: '云梯暗渡',
    blocks: [
      { id: 'caocao', type: 'caocao', x: 3, y: 1, width: 2, height: 2 },
      { id: 'v1', type: 'v-general', x: 0, y: 2, width: 1, height: 2 },
      { id: 'v2', type: 'v-general', x: 2, y: 2, width: 1, height: 2 },
      { id: 'v3', type: 'v-general', x: 1, y: 1, width: 1, height: 2 },
      { id: 'h1', type: 'h-general', x: 0, y: 0, width: 2, height: 1 },
      { id: 'h2', type: 'h-general', x: 3, y: 0, width: 2, height: 1 },
      { id: 's1', type: 'soldier', x: 2, y: 0, width: 1, height: 1 },
      { id: 's2', type: 'soldier', x: 1, y: 3, width: 1, height: 1 },
      { id: 's3', type: 'soldier', x: 0, y: 1, width: 1, height: 1 },
      { id: 's4', type: 'soldier', x: 3, y: 3, width: 1, height: 1 },
    ],
    minSteps: 34,
  },
  {
    id: 65,
    name: '破阵前夜',
    blocks: [
      { id: 'caocao', type: 'caocao', x: 2, y: 0, width: 2, height: 2 },
      { id: 'v1', type: 'v-general', x: 4, y: 0, width: 1, height: 2 },
      { id: 'v2', type: 'v-general', x: 0, y: 0, width: 1, height: 2 },
      { id: 'v3', type: 'v-general', x: 1, y: 1, width: 1, height: 2 },
      { id: 'v4', type: 'v-general', x: 2, y: 2, width: 1, height: 2 },
      { id: 'v5', type: 'v-general', x: 0, y: 2, width: 1, height: 2 },
      { id: 's1', type: 'soldier', x: 4, y: 3, width: 1, height: 1 },
      { id: 's2', type: 'soldier', x: 1, y: 3, width: 1, height: 1 },
      { id: 's3', type: 'soldier', x: 3, y: 2, width: 1, height: 1 },
    ],
    minSteps: 34,
  },
  {
    id: 66,
    name: '虎口脱险',
    blocks: [
      { id: 'caocao', type: 'caocao', x: 3, y: 0, width: 2, height: 2 },
      { id: 'v1', type: 'v-general', x: 0, y: 2, width: 1, height: 2 },
      { id: 'v2', type: 'v-general', x: 0, y: 0, width: 1, height: 2 },
      { id: 'v3', type: 'v-general', x: 4, y: 2, width: 1, height: 2 },
      { id: 'h1', type: 'h-general', x: 1, y: 0, width: 2, height: 1 },
      { id: 'h2', type: 'h-general', x: 2, y: 2, width: 2, height: 1 },
      { id: 's1', type: 'soldier', x: 1, y: 2, width: 1, height: 1 },
      { id: 's2', type: 'soldier', x: 2, y: 1, width: 1, height: 1 },
      { id: 's3', type: 'soldier', x: 3, y: 3, width: 1, height: 1 },
      { id: 's4', type: 'soldier', x: 1, y: 3, width: 1, height: 1 },
    ],
    minSteps: 37,
  },
  {
    id: 67,
    name: '万军取道',
    blocks: [
      { id: 'caocao', type: 'caocao', x: 2, y: 0, width: 2, height: 2 },
      { id: 'v1', type: 'v-general', x: 0, y: 1, width: 1, height: 2 },
      { id: 'h1', type: 'h-general', x: 2, y: 3, width: 2, height: 1 },
      { id: 'h2', type: 'h-general', x: 0, y: 0, width: 2, height: 1 },
      { id: 'h3', type: 'h-general', x: 1, y: 2, width: 2, height: 1 },
      { id: 'h4', type: 'h-general', x: 0, y: 3, width: 2, height: 1 },
      { id: 's1', type: 'soldier', x: 4, y: 2, width: 1, height: 1 },
      { id: 's2', type: 'soldier', x: 4, y: 3, width: 1, height: 1 },
      { id: 's3', type: 'soldier', x: 1, y: 1, width: 1, height: 1 },
      { id: 's4', type: 'soldier', x: 4, y: 0, width: 1, height: 1 },
    ],
    minSteps: 38,
  },
  {
    id: 68,
    name: '锁阵开门',
    blocks: [
      { id: 'caocao', type: 'caocao', x: 0, y: 0, width: 2, height: 2 },
      { id: 'v1', type: 'v-general', x: 0, y: 2, width: 1, height: 2 },
      { id: 'v2', type: 'v-general', x: 2, y: 2, width: 1, height: 2 },
      { id: 'v3', type: 'v-general', x: 1, y: 2, width: 1, height: 2 },
      { id: 'h1', type: 'h-general', x: 3, y: 1, width: 2, height: 1 },
      { id: 'h2', type: 'h-general', x: 3, y: 3, width: 2, height: 1 },
      { id: 's1', type: 'soldier', x: 2, y: 1, width: 1, height: 1 },
      { id: 's2', type: 'soldier', x: 3, y: 0, width: 1, height: 1 },
      { id: 's3', type: 'soldier', x: 3, y: 2, width: 1, height: 1 },
      { id: 's4', type: 'soldier', x: 4, y: 2, width: 1, height: 1 },
    ],
    minSteps: 43,
  },
  {
    id: 69,
    name: '千回百转',
    blocks: [
      { id: 'caocao', type: 'caocao', x: 2, y: 1, width: 2, height: 2 },
      { id: 'v1', type: 'v-general', x: 0, y: 0, width: 1, height: 2 },
      { id: 'v2', type: 'v-general', x: 1, y: 1, width: 1, height: 2 },
      { id: 'v3', type: 'v-general', x: 4, y: 2, width: 1, height: 2 },
      { id: 'h1', type: 'h-general', x: 0, y: 3, width: 2, height: 1 },
      { id: 'h2', type: 'h-general', x: 2, y: 3, width: 2, height: 1 },
      { id: 's1', type: 'soldier', x: 4, y: 1, width: 1, height: 1 },
      { id: 's2', type: 'soldier', x: 3, y: 0, width: 1, height: 1 },
      { id: 's3', type: 'soldier', x: 4, y: 0, width: 1, height: 1 },
      { id: 's4', type: 'soldier', x: 2, y: 0, width: 1, height: 1 },
    ],
    minSteps: 46,
  },
  {
    id: 70,
    name: '天堑通途',
    blocks: [
      { id: 'caocao', type: 'caocao', x: 0, y: 0, width: 2, height: 2 },
      { id: 'v1', type: 'v-general', x: 3, y: 0, width: 1, height: 2 },
      { id: 'v2', type: 'v-general', x: 2, y: 0, width: 1, height: 2 },
      { id: 'v3', type: 'v-general', x: 4, y: 1, width: 1, height: 2 },
      { id: 'h1', type: 'h-general', x: 0, y: 2, width: 2, height: 1 },
      { id: 'h2', type: 'h-general', x: 2, y: 2, width: 2, height: 1 },
      { id: 's1', type: 'soldier', x: 0, y: 3, width: 1, height: 1 },
      { id: 's2', type: 'soldier', x: 4, y: 3, width: 1, height: 1 },
      { id: 's3', type: 'soldier', x: 2, y: 3, width: 1, height: 1 },
      { id: 's4', type: 'soldier', x: 4, y: 0, width: 1, height: 1 },
    ],
    minSteps: 46,
  },
  {
    id: 71,
    name: '欲罢不能',
    blocks: [
      { id: 'caocao', type: 'caocao', x: 1, y: 0, width: 2, height: 2 },
      { id: 'h1', type: 'h-general', x: 0, y: 2, width: 2, height: 1 },
      { id: 'h2', type: 'h-general', x: 3, y: 2, width: 2, height: 1 },
      { id: 'h3', type: 'h-general', x: 1, y: 3, width: 2, height: 1 },
      { id: 'v1', type: 'v-general', x: 0, y: 0, width: 1, height: 2 },
      { id: 'v2', type: 'v-general', x: 4, y: 0, width: 1, height: 2 },
      { id: 's1', type: 'soldier', x: 2, y: 2, width: 1, height: 1 },
      { id: 's2', type: 'soldier', x: 4, y: 3, width: 1, height: 1 },
      { id: 's3', type: 'soldier', x: 3, y: 3, width: 1, height: 1 },
    ],
    minSteps: 47,
  },
  {
    id: 72,
    name: '最后屏障',
    blocks: [
      { id: 'caocao', type: 'caocao', x: 2, y: 0, width: 2, height: 2 },
      { id: 'v1', type: 'v-general', x: 2, y: 2, width: 1, height: 2 },
      { id: 'v2', type: 'v-general', x: 4, y: 1, width: 1, height: 2 },
      { id: 'v3', type: 'v-general', x: 1, y: 2, width: 1, height: 2 },
      { id: 'h1', type: 'h-general', x: 3, y: 3, width: 2, height: 1 },
      { id: 'h2', type: 'h-general', x: 0, y: 0, width: 2, height: 1 },
      { id: 's1', type: 'soldier', x: 0, y: 2, width: 1, height: 1 },
      { id: 's2', type: 'soldier', x: 4, y: 0, width: 1, height: 1 },
      { id: 's3', type: 'soldier', x: 3, y: 2, width: 1, height: 1 },
      { id: 's4', type: 'soldier', x: 0, y: 3, width: 1, height: 1 },
    ],
    minSteps: 50,
  },
  {
    id: 73,
    name: '绝地反击',
    blocks: [
      { id: 'caocao', type: 'caocao', x: 0, y: 0, width: 2, height: 2 },
      { id: 'v1', type: 'v-general', x: 3, y: 1, width: 1, height: 2 },
      { id: 'h1', type: 'h-general', x: 2, y: 0, width: 2, height: 1 },
      { id: 'h2', type: 'h-general', x: 3, y: 3, width: 2, height: 1 },
      { id: 'h3', type: 'h-general', x: 0, y: 2, width: 2, height: 1 },
      { id: 'h4', type: 'h-general', x: 1, y: 3, width: 2, height: 1 },
      { id: 's1', type: 'soldier', x: 2, y: 2, width: 1, height: 1 },
      { id: 's2', type: 'soldier', x: 0, y: 3, width: 1, height: 1 },
      { id: 's3', type: 'soldier', x: 4, y: 0, width: 1, height: 1 },
      { id: 's4', type: 'soldier', x: 4, y: 1, width: 1, height: 1 },
    ],
    minSteps: 60,
  },
  {
    id: 74,
    name: '水泄不通',
    blocks: [
      { id: 'caocao', type: 'caocao', x: 1, y: 0, width: 2, height: 2 },
      { id: 'v1', type: 'v-general', x: 0, y: 0, width: 1, height: 2 },
      { id: 'v2', type: 'v-general', x: 3, y: 0, width: 1, height: 2 },
      { id: 'v3', type: 'v-general', x: 4, y: 2, width: 1, height: 2 },
      { id: 'v4', type: 'v-general', x: 3, y: 2, width: 1, height: 2 },
      { id: 'h1', type: 'h-general', x: 1, y: 2, width: 2, height: 1 },
      { id: 's1', type: 'soldier', x: 4, y: 0, width: 1, height: 1 },
      { id: 's2', type: 'soldier', x: 4, y: 1, width: 1, height: 1 },
      { id: 's3', type: 'soldier', x: 1, y: 3, width: 1, height: 1 },
      { id: 's4', type: 'soldier', x: 2, y: 3, width: 1, height: 1 },
    ],
    minSteps: 69,
  },
  {
    id: 75,
    name: '终局破围',
    blocks: [
      { id: 'caocao', type: 'caocao', x: 3, y: 2, width: 2, height: 2 },
      { id: 'v1', type: 'v-general', x: 2, y: 0, width: 1, height: 2 },
      { id: 'h1', type: 'h-general', x: 0, y: 3, width: 2, height: 1 },
      { id: 'h2', type: 'h-general', x: 1, y: 2, width: 2, height: 1 },
      { id: 'h3', type: 'h-general', x: 0, y: 0, width: 2, height: 1 },
      { id: 'h4', type: 'h-general', x: 3, y: 0, width: 2, height: 1 },
      { id: 's1', type: 'soldier', x: 0, y: 1, width: 1, height: 1 },
      { id: 's2', type: 'soldier', x: 0, y: 2, width: 1, height: 1 },
      { id: 's3', type: 'soldier', x: 3, y: 1, width: 1, height: 1 },
      { id: 's4', type: 'soldier', x: 1, y: 1, width: 1, height: 1 },
    ],
    minSteps: 100,
  },
];

module.exports = {
  LEVELS,
  BLOCK_COLORS,
};
